// <auto-generated />
using System;
using FinanceControl.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceControl.Infrastructure.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20231122032850_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FinancaControl.Domain.Entities.AccountsPay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ContasPagarId");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVencimento");

                    b.Property<bool>("Pay")
                        .HasColumnType("bool")
                        .HasColumnName("Pago");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Fornecedor");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.ToTable("ContasPagar", (string)null);
                });

            modelBuilder.Entity("FinancaControl.Domain.Entities.AccountsReceive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ContasReceberId");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClienteId");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVencimento");

                    b.Property<bool>("Received")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Recebido");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.ToTable("ContasReceber", (string)null);
                });

            modelBuilder.Entity("FinancaControl.Domain.Entities.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ClienteId");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("TEXT")
                        .HasColumnName("Desconto");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVencimento");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT")
                        .HasColumnName("Observacao");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefone");

                    b.Property<string>("Recommendation")
                        .HasColumnType("TEXT")
                        .HasColumnName("Indicacao");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("FinancaControl.Domain.Entities.Servers", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ServidorId");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Contato");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NomeServidor");

                    b.Property<string>("Observation")
                        .HasColumnType("TEXT")
                        .HasColumnName("Observacao");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Site");

                    b.HasKey("Id");

                    b.ToTable("Servidores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
